// utils/genreMapping.js

// Mapping user-friendly genre names to Spotify genres
export const genreMap = {
  Acoustic: "acoustic",
  Afro: "afrobeat",
  "Alternative Rock": "alt-rock",
  Alternative: "alternative",
  Ambient: "ambient",
  Blues: "blues",
  Brazil: "brazil",
  Breaks: "breakbeat",
  British: "british",
  Chicago: "chicago-house",
  Classical: "classical",
  Club: "club",
  Dance: "dance",
  Dancehall: "dancehall",
  Deep: "deep-house",
  Detroit: "detroit-techno",
  Dub: "dub",
  "Dubstep post": "post-dubstep",
  "Drum and Bass": "drum-and-bass",
  EDM: "edm",
  Electronic: "electronic",
  Garage: "garage",
  German: "german",
  Groove: "groove",
  Hardcore: "hardcore",
  Hardstyle: "hardstyle",
  "Hip Hop": "hip-hop",
  House: "house",
  Jazz: "jazz",
  Minimal: "minimal-techno",
  Metal: "metal",
  Pop: "pop",
  Reggae: "reggae",
  Reggaeton: "reggaeton",
  Rock: "rock",
  Techno: "techno",
  Trance: "trance",

  // Add more mappings as needed
};
